#!/usr/bin/env python3
"""Build Knowledge System v2 files for CumulativeWebInc/cwi-learn.

Reads the fleet lineage registry (JSONL, one object per product) and generates:
  id/product/<slug>            permanent @id JSON-LD entity files (extensionless, resolvable)
  id/organization/cumulative-web-inc, id/artist/that-boy-hi-hat,
  id/dataset/lineage-registry-2026-10-01, id/index.html
  ai/ai-index.json             schema.org DataCatalog — the machine front door
  ai/entity-index.json         @id -> {type, name, url} map
  graph/ontology.jsonld        controlled relationship vocabulary (16 terms) + JSON-LD @context
  schemas/{product,entity,provenance,claim}.json
  validation/{validate.py,validation-rules.json}   (report generated by validator run)

Then patches (additive only): catalog.json, graph.json, kit.json, llms.txt,
.well-known/agent-card.json with knowledge-system pointers.

Usage: build-knowledge-v2.py --registry <path> --repo <path>
"""
import argparse, copy, datetime, html, json, os, re, sys

BASE = "https://cumulativewebinc.github.io/cwi-learn"
REPO = "https://github.com/CumulativeWebInc/cwi-learn"
TODAY = "2026-10-01"
VERSION = "2.0.0"

ONTOLOGY_TERMS = [
    ("developedBy", "https://schema.org/developer", "The organization or person that developed the entity."),
    ("createdBy", "https://schema.org/creator", "The person or organization that created the entity."),
    ("usesSoftware", None, "The entity uses the referenced software."),
    ("usesTechnology", None, "The entity uses the referenced technology."),
    ("partOf", "https://schema.org/isPartOf", "The entity is part of the referenced larger entity."),
    ("contains", "https://schema.org/hasPart", "The entity contains the referenced entity."),
    ("dependsOn", None, "The entity depends on the referenced entity to function."),
    ("builtWith", None, "The entity was built with the referenced tool/framework."),
    ("publishedBy", "https://schema.org/publisher", "The organization that published the entity."),
    ("distributedBy", None, "The organization that distributes the entity."),
    ("relatedTo", None, "Generic association when no narrower term applies."),
    ("derivedFrom", "https://schema.org/isBasedOn", "The entity is derived from the referenced entity."),
    ("versionOf", None, "The entity is a version of the referenced entity."),
    ("precedes", None, "The entity comes before the referenced entity in a sequence."),
    ("follows", None, "The entity comes after the referenced entity in a sequence."),
    ("supports", None, "The entity supports the referenced entity or program."),
    ("implements", None, "The entity implements the referenced specification/protocol."),
]
ONTOLOGY_URL = f"{BASE}/graph/ontology.jsonld"
ONTOLOGY_IRI = lambda t: f"{BASE}/graph/ontology#{t}"
ID_BASE = f"{BASE}/id/"
ORG_ID = f"{BASE}/id/organization/cumulative-web-inc"
ARTIST_ID = f"{BASE}/id/artist/that-boy-hi-hat"
REGISTRY_ID = f"{BASE}/id/dataset/lineage-registry-2026-10-01"

# slug -> (schema.org type, description, url|None, extra relationships)
PRODUCTS = {
    "KingCode Lens": ("kingcode-lens", "WebApplication",
        "Web apps for Meta Ray-Ban Display glasses: simulator lab + 'Hey KingCode' voice agent. 123/123 tests green.",
        "https://cumulativewebinc.github.io/cwi-kingcode-lens", []),
    "CWI World Desktop": ("cwi-world-desktop", "SoftwareApplication",
        "Crystal-console 3D world desktop with voice command deck (Windows portable 2.0.2). Internal operator tool.",
        None, []),
    "SANQA": ("sanqa", "SoftwareApplication",
        "CWI flagship commercial software suite: Trust Verdict Checker + 5 instruments, x402 paid routes ($0.05-$0.25 USDC on Base).",
        None, []),
    "FredRock Writers Room": ("fredrock-writers-room", "WebApplication",
        "Private writing circle app: 10 writers recording origin stories toward a Snowfall-style series (FredRock).",
        None, []),
    "Legacy Story Collection Platform": ("legacy-story-collection-platform", "WebApplication",
        "Story ingestion platform: typed docs, scans, handwriting, voice become AI interview questions and publish-ready manuscripts. Voice-first MVP.",
        None, []),
    "Weekly Session Podcast Engine": ("weekly-session-podcast-engine", "SoftwareApplication",
        "Weekly session podcast engine: Rock-Rap Night pilot (183 Wilboi); press packet + 11-label music verifications ready.",
        None, []),
    "CWI-1 Walkman / Signal Boy": ("cwi-1-walkman-signal-boy", "Product",
        "CWI-1 wearable Walkman + Signal Boy (Agent Edition): the 24-track That Boy Hi Hat catalog as a machine-readable cartridge with an EQUIP flow and evaluation rubric for AI agents.",
        f"{BASE}/walkman/", [("relatedTo", ARTIST_ID, "Carries the 24-track That Boy Hi Hat catalog")]),
    "CODEX — The Logo Effect": ("codex-the-logo-effect", "Book",
        "Living book manuscript (The Logo Effect): every factual claim traceable to a dated memory or file. Pre-cycle until a milestone breakthrough verifies.",
        None, []),
    "777 Neon Nights": ("777-neon-nights", "VideoGame",
        "777 Neon Nights arcade game with anonymous player-device telemetry (R2 target: 25 unique player devices). Money-prize mode is compliance-gated.",
        None, []),
    "Barrel King": ("barrel-king", "VideoGame",
        "Barrel King arcade game (serves the R2 player-device funnel).",
        None, []),
    "Street Kings": ("street-kings", "VideoGame",
        "Street Kings fighting game (serves the R2 player-device funnel).",
        None, []),
    "Word Signal": ("word-signal", "VideoGame",
        "Word Signal word game with deterministic seeded generation (serves the R2 player-device funnel).",
        None, []),
    "Cover Pieces": ("cover-pieces", "VideoGame",
        "Cover Pieces puzzle game (serves the R2 player-device funnel).",
        None, []),
    "Crown Climb": ("crown-climb", "VideoGame",
        "Crown Climb arcade game (serves the R2 player-device funnel).",
        None, []),
    "White-Label Slot Machine": ("white-label-slot-machine", "VideoGame",
        "White-label slot machine: link engine proven live (Spotify/Apple Music/Amazon); sellable to artists and labels, not yet packaged for sale.",
        None, []),
    "TAG CITY 3D": ("tag-city-3d", "VideoGame",
        "TAG CITY 3D: pre-cycle, blocked on Black's call between specialist human hands or an AI image-to-3D pipeline.",
        None, []),
    "Full-Catalog Slots": ("full-catalog-slots", "VideoGame",
        "Full-Catalog Slots: plan only (business plan 2026-09-21); awaiting Black's approval before any build begins.",
        None, []),
    "radio-365": ("radio-365", "RadioStation",
        "Cumulative Radio 365: CWI's indie radio channel. Icecast 128 kbps live; listed across directories (TuneIn, Streamitter, radio-browser.info, Airable-confirmed, Live Online Radio).",
        "https://cumulative-radio-365.pages.dev",
        [("publishedBy", ORG_ID, "CWI's own station"), ("distributedBy", ORG_ID, "CWI operates the stream")]),
    "the-edit-storefront": ("the-edit-storefront", "Store",
        "THE EDIT storefront: R1 conversion engine #1 (Booth/Edit/Crate/Greenlight/Call Sheet). 0 orders; cycle stopped at 'selling, manual'.",
        None, []),
    "cwi-store": ("cwi-store", "Store",
        "CWI Store: R1 conversion engine #2. 3 Gumroad slots live ($19/$49/$149), 4 pending email-order. 0 orders.",
        None, []),
    "results-dashboard": ("results-dashboard", "WebApplication",
        "Results dashboard: R3 measurement infrastructure (evidence for R2/R3) — funnel stages, receipts, targets.",
        None, []),
    "pull-distribution-stats": ("pull-distribution-stats", "SoftwareApplication",
        "pull-distribution-stats skill: GitHub traffic + Hugging Face downloads + trust-log claims in one machine-readable dashboard JSON.",
        None, []),
    "meta-global-ai-developer-hackathon": ("meta-global-ai-developer-hackathon", "Event",
        "Meta Global AI Developer Hackathon entry (pre-cycle: applications not open; research and watch only).",
        None, []),
    "agent-a-thon": ("agent-a-thon", "Event",
        "Agent-a-thon hackathon entry (prep stopped at Black's personal taps; Sep-2026 Microsoft event).",
        None, []),
    "trust-verdict": ("trust-verdict", "SoftwareApplication",
        "Trust Verdict Engine v1.0.0: deterministic agent-trust scoring over ERC-8004, Needle Drop, and First Spin signals; returns insufficient-data instead of invented scores.",
        None, []),
    "cwi-agent-memory": ("cwi-agent-memory", "SoftwareApplication",
        "CWI agent memory system: AES-256 encrypted repo with L1 off-chain EAS attestations (chain anchor).",
        None, []),
    "project-nervous-system": ("project-nervous-system", "SoftwareApplication",
        "Project Nervous System: machine-readable enforcement layer for the Agent Operating Framework (28 schemas, 43/43 tests).",
        None, []),
    "gear-ledger": ("gear-ledger", "SoftwareApplication",
        "Gear Ledger: agent gear ledger CLI (Agent Deck).",
        None, []),
    "cwi-mcp-server": ("cwi-mcp-server", "SoftwareApplication",
        "CWI MCP server: catalog lookup tools for AI agents (Model Context Protocol).",
        None, []),
    "cwi-mcp-public": ("cwi-mcp-public", "SoftwareApplication",
        "CWI MCP public server: public MCP tools including trust_verdict.",
        None, []),
    "a2a-relay": ("a2a-relay", "SoftwareApplication",
        "A2A Relay: agent-to-agent message relay; the R3 intake channel (data/requests.log is the adoption metric).",
        None, []),
    "delibra": ("delibra", "SoftwareApplication",
        "Delibra: local-model interview engine (proven for the story platform) with self-heal and watchdog.",
        None, []),
    "skill-sentinel": ("skill-sentinel", "SoftwareApplication",
        "Skill Sentinel: live-on-Pages skill with try-in-browser UX.",
        "https://cumulativewebinc.github.io/cwi-skill-sentinel", []),
}

CONFIDENCE_VALUES = ["verified", "owner_confirmed", "claimed_unverified", "incomplete"]

def tests_confidence(tests, notes):
    import re
    t = (tests + " " + notes).lower()
    neg = ["no test suite", "not green", "no-suite", "plan only",
           "unverified", "no formal", "n/a -", "nothing to run", "no shippable",
           "honest smoke", "honest, not green"]
    if any(k in t for k in neg):
        return "claimed_unverified"
    if re.search(r"\bFAILS?\b", tests + " " + notes):  # uppercase FAIL/FAILS = a failing suite
        return "claimed_unverified"
    if re.search(r"\b(pass|passed|green|verified|live|fetched live|ok)\b", t):
        return "verified"
    return "claimed_unverified"

def record_confidence(row):
    if row.get("packaged") == "n" and "pre-cycle" in (row.get("notes") or "").lower():
        return "incomplete"
    return tests_confidence(row.get("tests") or "", row.get("notes") or "")

def prov(claim, value, source, date_modified, confidence, status, evidence=""):
    e = {"claim": claim, "value": value, "source": {"@id": source},
         "dateCreated": TODAY, "dateModified": date_modified,
         "version": VERSION, "confidence": confidence, "status": status}
    if evidence:
        e["evidence"] = evidence
    return e

def rel(term, target, note=""):
    r = {"rel": term, "@id": ONTOLOGY_IRI(term), "target": {"@id": target}}
    if note:
        r["note"] = note
    return r

def write_json(path, obj):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(obj, f, indent=2, ensure_ascii=False)
        f.write("\n")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--registry", required=True)
    ap.add_argument("--repo", required=True)
    a = ap.parse_args()
    repo = a.repo
    rows = [json.loads(l) for l in open(a.registry) if l.strip()]
    seen, entities = set(), {}

    # --- source dataset entity for the lineage registry itself ---
    write_json(os.path.join(repo, "id/dataset/lineage-registry-2026-10-01"), {
        "@context": "https://schema.org",
        "@id": REGISTRY_ID,
        "@type": "Dataset",
        "name": "CWI lineage registry (2026-10-01)",
        "description": ("Fleet-wide lineage retrofit records: 34 product rows, one JSON object per product "
                        "(product, result R1/R2/R3, who, channel, cta, end_number, cycle_stage, tests, "
                        "packaged, verified_at, notes). The provenance source for every product entity's "
                        "lineage claims."),
        "creator": {"@id": ORG_ID},
        "dateCreated": TODAY, "dateModified": TODAY, "version": VERSION,
        "url": REGISTRY_ID,
        "provenance": [prov("registry compiled", "34 product rows verified by lineage slice workers",
                            ORG_ID, TODAY, "verified", "complete",
                            "lineage-registry.jsonl, verified_at per row 2026-10-01")],
        "relationships": [rel("createdBy", ORG_ID, "Compiled by the CWI agent fleet")],
    })
    entities[REGISTRY_ID] = ("Dataset", "CWI lineage registry (2026-10-01)")

    # --- product entities ---
    for row in rows:
        name = row["product"]
        if name not in PRODUCTS:
            print(f"WARN: no product spec for {name!r}; skipping", file=sys.stderr)
            continue
        if name in seen:
            pass  # radio-365 appears twice (R1+R2): merge into one entity below
        seen.add(name)
    # merge duplicate rows (radio-365 R1+R2)
    merged = {}
    for row in rows:
        merged.setdefault(row["product"], []).append(row)

    for name, slug, stype, desc, url, extra_rels in [ (n,)+PRODUCTS[n] for n in PRODUCTS ]:
        if name not in merged:
            print(f"WARN: {name!r} has no lineage row; skipping", file=sys.stderr)
            continue
        eid = f"{BASE}/id/product/{slug}"
        provs, rels = [], [rel("developedBy", ORG_ID, "Built by Cumulative Web Inc")]
        lineage_blocks = []
        for row in merged[name]:
            conf = record_confidence(row)
            vdate = (row.get("verified_at") or TODAY)[:10]
            lineage_blocks.append({k: row.get(k) for k in
                ["product","result","who","channel","cta","end_number","cycle_stage","tests","packaged","verified_at","notes"]})
            provs.append(prov(
                f"lineage record ({row.get('result')})",
                f"{row.get('who','')} | {row.get('channel','')} | CTA: {row.get('cta','')}",
                REGISTRY_ID, vdate, conf, row.get("cycle_stage") or "unknown",
                (row.get("tests") or "")[:280]))
            provs.append(prov(
                f"conversion end number ({row.get('result')})",
                str(row.get("end_number")),
                REGISTRY_ID, vdate,
                "verified" if "verified" in str(row.get("end_number")).lower() or str(row.get("end_number")).strip() in ("0", "$0") else "claimed_unverified",
                row.get("cycle_stage") or "unknown",
                "as recorded in the lineage registry 2026-10-01"))
        for term, target, note in extra_rels:
            rels.append(rel(term, target, note))
        ent = {"@context": "https://schema.org", "@id": eid, "@type": stype,
               "name": name, "description": desc,
               "dateCreated": TODAY, "dateModified": TODAY, "version": VERSION,
               "provenance": provs, "relationships": rels, "lineage": lineage_blocks}
        if url:
            ent["url"] = url
        write_json(os.path.join(repo, f"id/product/{slug}"), ent)
        entities[eid] = (stype, name)

    # --- core entities ---
    write_json(os.path.join(repo, "id/organization/cumulative-web-inc"), {
        "@context": "https://schema.org", "@id": ORG_ID, "@type": "Organization",
        "name": "Cumulative Web Inc", "alternateName": "CWI",
        "description": "Independent music company. Management and creative for alternative rap / Post-Trap Futurism.",
        "url": "https://cumulativeweb.com", "logo": f"{BASE}/logo.jpg",
        "email": "hp@cumulativeweb.com",
        "dateCreated": TODAY, "dateModified": TODAY, "version": VERSION,
        "provenance": [prov("organization identity", "Cumulative Web Inc",
                            REGISTRY_ID, TODAY, "verified", "active",
                            "established across catalog.json, kit.json, llms.txt since 2026-09-15")],
        "relationships": [],
    })
    entities[ORG_ID] = ("Organization", "Cumulative Web Inc")
    write_json(os.path.join(repo, "id/artist/that-boy-hi-hat"), {
        "@context": "https://schema.org", "@id": ARTIST_ID, "@type": "MusicGroup",
        "name": "That Boy Hi Hat",
        "description": "Alternative rap artist (Post-Trap Futurism), based in Frederick, MD. 27-track catalog; breakout record 'Zooted Zone'.",
        "url": "https://open.spotify.com/artist/2f9j460EwjfvjYp3trBcb7",
        "genre": ["alternative rap", "Post-Trap Futurism"],
        "dateCreated": TODAY, "dateModified": TODAY, "version": VERSION,
        "provenance": [prov("artist identity", "That Boy Hi Hat",
                            REGISTRY_ID, TODAY, "verified", "active",
                            "catalog.json / kit.json artist block; Spotify artist ID 2f9j460EwjfvjYp3trBcb7")],
        "relationships": [rel("relatedTo", ORG_ID, "Label/management: Cumulative Web Inc")],
    })
    entities[ARTIST_ID] = ("MusicGroup", "That Boy Hi Hat")

    # --- ontology ---
    ctx_terms = {t: {"@id": ONTOLOGY_IRI(t), "@type": "@id"} for t, _, _ in ONTOLOGY_TERMS}
    write_json(os.path.join(repo, "graph/ontology.jsonld"), {
        "@context": ctx_terms,
        "@id": ONTOLOGY_URL, "@type": "Ontology",
        "name": "CWI Knowledge Graph Relationship Ontology",
        "description": ("Controlled relationship vocabulary for the CWI knowledge system. "
                        "New relationships MUST use one of these terms; no free-text relation names."),
        "version": "1.0.0", "dateCreated": TODAY, "dateModified": TODAY,
        "publisher": {"@id": ORG_ID},
        "relations": [
            {"name": t, "@id": ONTOLOGY_IRI(t),
             **({"schemaOrg": s} if s else {}), "description": d}
            for t, s, d in ONTOLOGY_TERMS
        ],
    })

    # --- schemas ---
    sdir = os.path.join(repo, "schemas")
    write_json(os.path.join(sdir, "provenance.json"), {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"{BASE}/schemas/provenance.json", "title": "CWI provenance entry",
        "type": "object",
        "required": ["claim", "value", "source", "dateCreated", "dateModified", "version", "confidence", "status"],
        "properties": {
            "claim": {"type": "string"}, "value": {"type": "string"},
            "source": {"type": "object", "required": ["@id"],
                       "properties": {"@id": {"type": "string", "format": "uri"}}},
            "dateCreated": {"type": "string"}, "dateModified": {"type": "string"},
            "version": {"type": "string"},
            "confidence": {"type": "string", "enum": CONFIDENCE_VALUES},
            "status": {"type": "string"}, "evidence": {"type": "string"}},
    })
    write_json(os.path.join(sdir, "claim.json"), {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"{BASE}/schemas/claim.json", "title": "CWI claim",
        "type": "object",
        "required": ["claim", "value", "provenance"],
        "properties": {
            "claim": {"type": "string"}, "value": {"type": "string"},
            "provenance": {"type": "array", "minItems": 1,
                           "items": {"$ref": "provenance.json"}}},
    })
    write_json(os.path.join(sdir, "entity.json"), {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"{BASE}/schemas/entity.json", "title": "CWI knowledge entity",
        "type": "object",
        "required": ["@context", "@id", "@type", "name", "description",
                     "dateCreated", "dateModified", "version", "provenance"],
        "properties": {
            "@context": {"type": "string"}, "@id": {"type": "string", "format": "uri"},
            "@type": {"type": "string"}, "name": {"type": "string"},
            "description": {"type": "string"}, "url": {"type": "string"},
            "dateCreated": {"type": "string"}, "dateModified": {"type": "string"},
            "version": {"type": "string"},
            "provenance": {"type": "array", "minItems": 1, "items": {"$ref": "provenance.json"}},
            "relationships": {"type": "array", "items": {"type": "object",
                "required": ["rel", "@id", "target"],
                "properties": {"rel": {"type": "string", "enum": [t for t, _, _ in ONTOLOGY_TERMS]},
                              "@id": {"type": "string", "format": "uri"},
                              "target": {"type": "object", "required": ["@id"]},
                              "note": {"type": "string"}}}},
        },
    })
    write_json(os.path.join(sdir, "product.json"), {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"{BASE}/schemas/product.json",
        "title": "CWI retrofit packaging template (product)",
        "description": ("The packaging standard for every retrofitted CWI product: permanent @id, "
                        "schema.org type, lineage-traced provenance on every claim. "
                        "All future retrofits ship one conforming file at id/product/<slug>."),
        "type": "object",
        "required": ["@context", "@id", "@type", "name", "description",
                     "dateCreated", "dateModified", "version", "provenance",
                     "relationships", "lineage"],
        "properties": {
            "@context": {"type": "string"}, "@id": {"type": "string", "format": "uri"},
            "@type": {"type": "string"}, "name": {"type": "string"},
            "description": {"type": "string"}, "url": {"type": "string"},
            "dateCreated": {"type": "string"}, "dateModified": {"type": "string"},
            "version": {"type": "string"},
            "provenance": {"type": "array", "minItems": 1, "items": {"$ref": "provenance.json"}},
            "relationships": {"type": "array", "items": {"type": "object",
                "required": ["rel", "@id", "target"],
                "properties": {"rel": {"type": "string", "enum": [t for t, _, _ in ONTOLOGY_TERMS]},
                              "@id": {"type": "string", "format": "uri"},
                              "target": {"type": "object", "required": ["@id"]},
                              "note": {"type": "string"}}}},
            "lineage": {"type": "array", "minItems": 1, "items": {"type": "object",
                "required": ["product", "result", "who", "channel", "cta", "end_number",
                             "cycle_stage", "tests", "packaged", "verified_at", "notes"]}},
        },
    })

    # --- ai-index.json (machine front door) ---
    datasets = [
        {"@id": f"{BASE}/catalog.json", "@type": "Dataset", "name": "CWI catalog.json",
         "description": "35-track machine-readable catalog (artist, tracks, placements, label presence)."},
        {"@id": f"{BASE}/graph.json", "@type": "Dataset", "name": "CWI graph.json",
         "description": "Catalog knowledge graph: nodes + edges (music catalog; legacy snake_case rels grandfathered, see rel_legend)."},
        {"@id": f"{BASE}/kit.json", "@type": "Dataset", "name": "CWI kit.json",
         "description": "Agent kit: citation guidance, verified proof points, claimed-but-unverified list."},
        {"@id": REGISTRY_ID, "@type": "Dataset", "name": "CWI lineage registry (2026-10-01)",
         "description": "34 fleet-retrofit product lineage records; provenance source for product entities."},
        {"@id": f"{BASE}/ai/entity-index.json", "@type": "Dataset", "name": "entity-index.json",
         "description": "Every permanent @id mapped to type, name, and resolvable URL."},
        {"@id": ONTOLOGY_URL, "@type": "Ontology", "name": "Relationship ontology",
         "description": "Controlled relationship vocabulary (16 terms); doubles as JSON-LD @context."},
        {"@id": f"{BASE}/schemas/product.json", "@type": "Dataset", "name": "Retrofit packaging schema",
         "description": "JSON Schema: the per-product JSON-LD packaging template all retrofits conform to."},
    ]
    write_json(os.path.join(repo, "ai/ai-index.json"), {
        "@context": "https://schema.org",
        "@id": f"{BASE}/ai/ai-index.json", "@type": "DataCatalog",
        "name": "CWI Knowledge System — machine front door",
        "description": ("Start here. Every dataset, entity, schema, and document a machine needs to "
                        "discover, verify, and equip CWI software and catalog data. One canonical data layer."),
        "publisher": {"@id": ORG_ID},
        "version": VERSION, "dateCreated": TODAY, "dateModified": TODAY,
        "idPattern": f"{BASE}/id/<type>/<slug>",
        "idResolution": ("Fetch the @id URL directly; the body is JSON-LD. Human directory at "
                         f"{BASE}/id/ . Entity map at {BASE}/ai/entity-index.json ."),
        "provenancePolicy": ("Every claim carries source @id, dateCreated/dateModified, version, "
                             "confidence (verified | owner_confirmed | claimed_unverified | incomplete), "
                             "and status. 'verified' is used only for actually-verified facts."),
        "relationshipPolicy": (f"New relationships use only the controlled vocabulary at {ONTOLOGY_URL} . "
                               "No free-text relation names."),
        "dataset": datasets,
        "mainEntity": {"@id": f"{BASE}/ai/entity-index.json"},
    })
    write_json(os.path.join(repo, "ai/entity-index.json"), {
        "@context": "https://schema.org",
        "@id": f"{BASE}/ai/entity-index.json", "@type": "Dataset",
        "name": "CWI entity index", "version": VERSION,
        "dateCreated": TODAY, "dateModified": TODAY,
        "publisher": {"@id": ORG_ID},
        "entities": [{"@id": eid, "@type": t, "name": n, "url": eid}
                     for eid, (t, n) in sorted(entities.items())],
        "count": len(entities),
    })

    # --- id/index.html human directory ---
    cards = "\n".join(
        f'<li><a href="{eid}"><code>{eid.replace(BASE+"/id/","")}</code></a> — <b>{html.escape(n)}</b> <i>({t})</i></li>'
        for eid, (t, n) in sorted(entities.items()))
    with open(os.path.join(repo, "id/index.html"), "w") as f:
        f.write(f"""<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<title>CWI Knowledge System — entity directory</title></head><body>
<h1>Permanent entity IDs</h1>
<p>Pattern: <code>{BASE}/id/&lt;type&gt;/&lt;slug&gt;</code>. Fetch any @id URL directly — the body is JSON-LD.</p>
<p>Machine front door: <a href="{BASE}/ai/ai-index.json">ai-index.json</a> ·
Ontology: <a href="{ONTOLOGY_URL}">ontology.jsonld</a> ·
Packaging schema: <a href="{BASE}/schemas/product.json">product.json</a></p>
<ul>{cards}</ul>
<p>By Cumulative Web Inc · knowledge system v{VERSION} · {TODAY}</p>
</body></html>
""")

    # --- additive patches to existing canonical routes ---
    def patch_json(relpath, extra):
        p = os.path.join(repo, relpath)
        d = json.load(open(p))
        d.update(extra)
        write_json(p, d)

    ks = {"version": VERSION, "aiIndex": f"{BASE}/ai/ai-index.json",
          "entityIndex": f"{BASE}/ai/entity-index.json",
          "ontology": ONTOLOGY_URL, "idBase": ID_BASE,
          "packagingSchema": f"{BASE}/schemas/product.json"}
    patch_json("catalog.json", {"@context": "https://schema.org", "@id": f"{BASE}/catalog.json",
                                "@type": "Dataset", "knowledgeSystem": ks})
    patch_json("kit.json", {"@context": "https://schema.org", "@id": f"{BASE}/kit.json",
                            "@type": "Dataset", "knowledgeSystem": ks})
    patch_json(".well-known/agent-card.json",
               {"@id": f"{BASE}/.well-known/agent-card.json", "knowledgeSystem": ks})

    # graph.json: ontology pointer + legacy rel legend (grandfathered, not rewritten)
    gp = os.path.join(repo, "graph.json")
    g = json.load(open(gp))
    legend = {
        "performed_by": "relatedTo", "has_track": "contains", "included_in": "partOf",
        "released": "publishedBy", "streaming_on": "distributedBy", "exemplar_of": "relatedTo",
        "placed_on": "relatedTo", "produced_by": "createdBy", "managed_by": "relatedTo",
        "defines": "relatedTo", "associated": "relatedTo", "located_in": "relatedTo",
        "based_in": "relatedTo", "co_produced_by": "createdBy", "recorded_at": "relatedTo",
        "mixed_and_mastered_by": "createdBy", "released_on": "distributedBy",
        "artwork_for": "relatedTo", "features_audio": "contains", "uses_artwork": "usesSoftware",
        "operated_by": "relatedTo", "associated_artist": "relatedTo", "has_release": "contains",
        "tagged": "relatedTo", "by_artist": "createdBy",
    }
    g.update({"@context": ONTOLOGY_URL, "@id": f"{BASE}/graph.json",
              "ontology": ONTOLOGY_URL, "id_base": ID_BASE,
              "relationship_policy": ("Edges added after 2026-10-01 MUST use the controlled vocabulary at "
                                      f"{ONTOLOGY_URL} . Legacy music-catalog rels (snake_case) predate it and are "
                                      "grandfathered via rel_legend; they are NOT rewritten in this pass."),
              "rel_legend": legend, "knowledgeSystem": ks})
    write_json(gp, g)

    # llms.txt: machine front door section at top
    lp = os.path.join(repo, "llms.txt")
    txt = open(lp).read()
    banner = (f"""# MACHINE FRONT DOOR (knowledge system v{VERSION}, {TODAY})

> Start at {BASE}/ai/ai-index.json — the DataCatalog listing every dataset, entity,
> schema, and document. Permanent entity IDs: {BASE}/id/<type>/<slug> (fetch the @id
> URL directly; body is JSON-LD). Relationship vocabulary: {ONTOLOGY_URL} (16
> controlled terms; no free-text relation names). Provenance: every claim carries source
> @id + dates + version + confidence (verified | owner_confirmed | claimed_unverified |
> incomplete) + status. Retrofit packaging schema: {BASE}/schemas/product.json.

""")
    if "MACHINE FRONT DOOR" not in txt:
        open(lp, "w").write(banner + txt)

    print(f"entities: {len(entities)} | products: {len(PRODUCTS)}")
    print("done.")

if __name__ == "__main__":
    main()
